[versions]

kotlin = "1.9.10"
androidGradlePlugin = "8.1.2"
compose = "1.5.1"
composeActivity = "1.8.0"
appcompat = "1.6.1"
atomicfu = "0.17.3"
kover = "0.6.1"

[libraries]

android-composeActivity = { module = "androidx.activity:activity-compose", version.ref = "composeActivity" }
android-composeToolingPreview = { module = "androidx.compose.ui:ui-tooling-preview", version.ref = "compose" }
android-appcompat = { module = "androidx.appcompat:appcompat", version.ref = "appcompat" }

# Classpaths
classpaths-atomicfu = { module = "org.jetbrains.kotlinx:atomicfu-gradle-plugin", version.ref = "atomicfu" }

[plugins]

kotlinMultiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
compose = { id = "org.jetbrains.compose", version.ref = "compose" }
androidApplication = { id = "com.android.application", version.ref = "androidGradlePlugin" }
atomicfu = { id = "kotlinx-atomicfu" }
kover = { id = "org.jetbrains.kotlinx.kover", version.ref = "kover" }
