name: TraceFit CI

on:
  push:
    branches:
      - develop
  pull_request:

concurrency:
  group: ${{ github.ref == 'refs/heads/develop' && 'develop' || github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/develop' }}

env:
  SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
  CI: true

jobs:

  GradleBuild:
    runs-on: macos-14
    outputs:
      status: ${{ steps.status.outputs.status }}
    steps:

      - name: Setup Gradle Repo
        uses: Oztechan/Global/actions/setup-gradle-repo@f2926167f4c8103dca1abd9cf2908c83733e1898

      - name: Assemble
        run: ./gradlew assemble

      - name: Cancel other jobs if this fails
        if: failure()
        uses: andymckay/cancel-action@0.5

      - name: Set Job Status
        id: status
        run: echo "status=success" >> $GITHUB_OUTPUT

  Quality:
    runs-on: macos-14
    outputs:
      status: ${{ steps.status.outputs.status }}
    steps:

      - name: Setup Gradle Repo
        uses: Oztechan/Global/actions/setup-gradle-repo@f2926167f4c8103dca1abd9cf2908c83733e1898

      - name: Run Quality Jobs
        run: ./gradlew check koverXmlReport --parallel

      - name: Upload Coverage Report
        uses: actions/upload-artifact@v4.4.0
        with:
          name: coverageReport
          path: build/reports/kover/report.xml

      - name: Cancel other jobs if this fails
        if: failure()
        uses: andymckay/cancel-action@0.5

      - name: Set Job Status
        id: status
        run: echo "status=success" >> $GITHUB_OUTPUT


  Notify:
    runs-on: ubuntu-latest
    needs: [ GradleBuild, Quality]
    if: always()
    steps:

      - name: Notify slack fail
        if: false == (needs.GradleBuild.outputs.status == 'success') ||
          false == (needs.Quality.outputs.status == 'success')
        uses: voxmedia/github-action-slack-notify-build@v1.6.0
        with:
          channel: tracefit-github
          status: FAILED
          color: danger
