name: TraceFit CI

on:
  push:
    branches:
      - develop
  pull_request:

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

env:
  SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
  CI: true

jobs:

  GradleBuild:
    runs-on: macos-13
    outputs:
      status: ${{ steps.status.outputs.status }}
    steps:

      - name: Clone Repo
        uses: actions/checkout@v4.1.1
        with:
          submodules: 'recursive'
          fetch-depth: 0

      - name: Set up JDK 17
        uses: actions/setup-java@v4.2.1
        with:
          java-version: 17
          distribution: 'temurin'

      - name: Assemble
        uses: gradle/gradle-build-action@v3.1.0
        with:
          arguments: assemble

      - name: Cancel other jobs if this fails
        if: failure()
        uses: andymckay/cancel-action@0.4

      - name: Set Job Status
        id: status
        run: echo "status=success" >> $GITHUB_OUTPUT

  Quality:
    runs-on: macos-13
    outputs:
      status: ${{ steps.status.outputs.status }}
    steps:

      - name: Clone Repo
        uses: actions/checkout@v4.1.1
        with:
          submodules: 'recursive'

      - name: Set up JDK 17
        uses: actions/setup-java@v4.2.1
        with:
          java-version: 17
          distribution: 'temurin'

      - name: Run Quality Jobs
        uses: gradle/gradle-build-action@v3.1.0
        with:
          arguments: check koverMergedXmlReport --parallel

      - name: Upload Coverage Report
        uses: actions/upload-artifact@v4.3.3
        with:
          name: coverageReport
          path: build/reports/kover/merged/xml/report.xml

      - name: Cancel other jobs if this fails
        if: failure()
        uses: andymckay/cancel-action@0.4

      - name: Set Job Status
        id: status
        run: echo "status=success" >> $GITHUB_OUTPUT


  Notify:
    runs-on: ubuntu-latest
    needs: [ GradleBuild, Quality]
    if: always()
    steps:

      - name: Notify slack fail
        if: false == (needs.GradleBuild.outputs.status == 'success') ||
          false == (needs.Quality.outputs.status == 'success')
        uses: voxmedia/github-action-slack-notify-build@v1.6.0
        with:
          channel: tracefit-github
          status: FAILED
          color: danger
