name: Project Automations
on:
  issues:
    types:
      - opened
      - reopened
  pull_request:
    types:
      - opened
      - ready_for_review
      - reopened
      - closed
      - converted_to_draft

jobs:
  ProjectAutomations:
    uses: Oztechan/actions/.github/workflows/project.yml@90e64a09fceeb765c80c5a226b3580dafc8c422c
    with:
      project_id: 6
    secrets: inherit
