name: Project Automations
on:
  issues:
    types:
      - opened
      - reopened
  pull_request:
    types:
      - opened
      - ready_for_review
      - reopened
      - closed
      - converted_to_draft

jobs:
  ProjectAutomations:
    uses: Oztechan/Global/.github/workflows/reusable-project.yml@761ee6a42abe9207af1a754cc94ee7376387ce30
    with:
      project_id: 6
    secrets: inherit
