name: Project Automations
on:
  issues:
    types:
      - opened
      - reopened
  pull_request:
    types:
      - opened
      - ready_for_review
      - reopened
      - closed
      - converted_to_draft

jobs:
  ProjectAutomations:
    uses: Oztechan/actions/.github/workflows/project.yml@add90676c3c8b3c3e998914bceb050cee69b74f3
    with:
      project_id: 6
    secrets: inherit
