name: Project Automations
on:
  issues:
    types:
      - opened
      - reopened
  pull_request:
    types:
      - opened
      - ready_for_review
      - reopened
      - closed
      - converted_to_draft

jobs:
  ProjectAutomations:
    uses: Oztechan/Global/.github/workflows/actions/project.yml@56bc4d957b28881427df078709420bb2abb2b37b
    with:
      project_id: 6
    secrets: inherit
